import 'dart:io';
import 'package:supabase/supabase.dart';

void main() async {
  print('🚀 Starting Bulk Card Seeding...');
  final envFile = File('.env');
  final envLines = await envFile.readAsLines();
  String? url;
  String? serviceKey;
  for (var line in envLines) {
    if (line.startsWith('SUPABASE_URL=')) url = line.split('=')[1];
    if (line.startsWith('SUPABASE_SERVICE_ROLE_KEY=')) serviceKey = line.split('=')[1];
  }
  
  final client = SupabaseClient(url!, serviceKey!);
  
  // 1. Fetch categories
  final categoriesData = await client.from('categories').select();
  final Map<String, String> categoryNameToId = {};
  for(var c in categoriesData) {
    categoryNameToId[c['name'].toString().toLowerCase()] = c['id'];
  }
  
  // 2. Fetch existing cards to extract their cover_image_url and color_value
  final existingCards = await client.from('cards').select();
  final Map<String, Map<String, dynamic>> categoryIdToCardDefaults = {};
  for(var c in existingCards) {
    categoryIdToCardDefaults[c['category_id']] = {
      'cover_image_url': c['cover_image_url'],
      'color_value': c['color_value']
    };
  }
  
  // 3. Delete existing cards
  print('🗑️ Deleting ${existingCards.length} dummy cards to make way for the 112 new variations...');
  await client.from('cards').delete().neq('id', '00000000-0000-0000-0000-000000000000');
  
  // 4. Parse TSV data
  final rawData = """Love	1	Every single day with you feels like a gift I never want to unwrap too quickly. I love you more than words can hold.	116	From the way you laugh at your own jokes to the way you hold my hand without thinking about it, every little thing you do makes me fall for you all over again. You are my favorite person to share silence with, my favorite person to share noise with, and my favorite person to share this whole beautiful, messy life with. Thank you for being exactly who you are, and.	366
Love	2	You are my today, my tomorrow, and every ordinary Tuesday in between. I love you more than I know how to say.	109	I used to think love was a feeling, but with you it has become a decision I make every morning when I wake up beside you. You make the hard days softer and the good days brighter, simply by being here. I love the way you see the world, the way you care for the people around you, and the way you still surprise me after all this time. Whatever life brings next.	361
Love	3	My heart found its home the day it found you. Thank you for loving me so gently and so fiercely all at once.	108	There is a quiet kind of magic in loving someone who knows your flaws and stays anyway, who has seen you at your worst and still reaches for your hand. That is you. You have taught me what patience looks like, what kindness sounds like, and what it means to be truly seen. I do not need grand gestures to know I am loved, because you show me in a hundred small ways every single day. I love you more than yesterday and not nearly as much as tomorrow.	450
Love	4	If loving you was a job, I would never ask for a single day off. You are my favorite person in this world.	106	I never planned on finding someone who fits so perfectly into the spaces I did not even know were empty, but here you are. You make coffee taste better, rainy days feel cozier, and hard conversations feel a little less scary because I know you are on my side. I love your mind, your heart, and the way you make an ordinary room feel like the best. Always yours.	361
Love	5	You are the calm in my chaos and the spark in my quiet moments. I love you today, tomorrow, and always, truly.	110	Some people search their whole lives for what we have, and I get to wake up next to it every single day. You have this way of making me feel completely at ease and completely alive at the same time, which should not be possible but somehow is. I love the conversations that last too long, the inside jokes nobody else understands, and the way you still get a little shy when I say I love you. You are my person, now and for every chapter still to come. You are.	461
Love	6	Loving you is the easiest thing I have ever done. Happy to be yours, today and every single day after this one.	111	You have this rare gift of making everyone around you feel safe, but especially me. When I am with you, I do not have to pretend to be anything other than exactly who I am, flaws and all, and that kind of freedom is the greatest love I have ever known. I love how you remember the little things, how you show up when it matters most, and how being loved by you feels like coming home no matter where we actually are. Here is to us, always and completely. You are, and always will be, my greatest love story. No matter what life brings, I choose.	545
Love	7	You make forever sound like a promise I actually want to keep. I love you more than these small words can say.	110	There is no version of my future that I imagine without you in it, sitting right beside me, making it better just by being there. You have this quiet strength that steadies me when things get hard and a warmth that makes even ordinary moments feel worth remembering. I fall in love with you again every time you laugh, every time you care for someone.	351
Love	8	Two hearts, one story, and I would not trade a single chapter of it. I love you more with every passing day.	108	Looking back at everything we have been through together, I am more certain than ever that you are exactly who I am supposed to be with. You have seen me change and grow and stumble, and you have loved me steadily through all of it without ever asking me to be someone else. I love building this life with you, one ordinary and extraordinary day at a time. Whatever comes next, I know we will figure it out together, because that is what we do best. Forever, my love. You are, and.	481
Congratulations	1	Congratulations on your incredible achievement! All that hard work and determination truly paid off in the end.	111	Watching you work toward this goal has been genuinely inspiring, and seeing you reach it feels like a win for everyone who knows you. You put in the effort when it was not easy, stayed focused when it would have been simple to give up, and now you get to enjoy the reward that comes from that kind of dedication. This is just the beginning of everything good that is coming your way. Take a.	391
Congratulations	2	Congratulations! This moment is the perfect proof that your hard work, patience, and persistence truly mattered.	112	Big achievements like this do not happen by accident, they happen because someone kept showing up even when it was tough, and that someone was you. I hope you are giving yourself full credit for everything it took to get here, because it was not easy and you made it look effortless anyway. Here is to celebrating this win loudly and to everything wonderful that this new chapter is going to bring. You deserve every bit of happiness heading your way. Congratulations again, truly well done.	491
Congratulations	3	What amazing news! Congratulations on reaching this milestone, you have every reason in the world to celebrate.	111	From the moment I heard the news, I could not stop smiling because I know exactly how much this means to you and how hard you worked to get here. Success like this is built on quiet effort that nobody else sees, the early mornings, the late nights, and the moments you kept going anyway. Now it is time to enjoy the results of all that dedication. May this achievement.	369
Congratulations	4	Congratulations on your big win! Your talent, effort, and heart shine through in everything that you achieve.	109	It takes a special kind of person to chase a goal with as much focus and heart as you did, and it takes an even more special person to make it look this graceful. I am so happy for you and so proud to know someone as driven and genuine as you are. This achievement is a reflection of everything good about how you approach life, and I hope it brings you a well deserved sense of pride. Enjoy every second of this celebration, you have absolutely earned it.	456
Congratulations	5	Congratulations! Here is to celebrating you, your effort, and this well deserved and hard earned success today.	111	Some wins matter more than others, and this is clearly one of those moments that deserves to be celebrated properly. You showed up, put in the work, and trusted yourself even when the outcome was not guaranteed, and that kind of courage deserves recognition. I hope today is filled with warm congratulations, good company, and the quiet satisfaction of knowing you did something truly great. Wishing you continued success and even more reasons to celebrate in the future. So happy for you, congratulations! This moment is proof of.	531
Congratulations	6	Way to go! Congratulations on this fantastic achievement, you should be incredibly proud of everything you built.	113	News this good deserves to be celebrated loudly, so consider this your official permission to feel proud, take a bow, and enjoy the moment fully. Achievements like yours do not happen without real sacrifice and real belief in yourself, even during the moments when it would have been easier to doubt it all. You pushed through anyway, and now you get to enjoy the reward. I hope this success brings you not just recognition, but.	429
Congratulations	7	Congratulations on this exciting achievement! Your dedication and hard work have truly paid off in every way.	109	There is something wonderful about watching someone work steadily toward a goal and then finally get to celebrate reaching it, and today that someone is you. I hope you take real pride in this moment, because it represents so much more than the final result, it represents every ounce of effort you put into getting here. May this be the start of even greater things ahead. Wishing you continued success, happiness, and many more milestones worth celebrating. Congratulations.	476
Congratulations	8	Big congratulations to you! May this achievement be the first of many wonderful successes still to come your way.	113	Achieving something this meaningful takes real commitment, and watching you push through the challenges to get here has been genuinely inspiring to witness. You did not just work hard, you worked smart, stayed patient, and trusted the process even when it was uncertain. That kind of resilience deserves to be celebrated fully and enjoyed completely. I hope this moment fills you with pride and.	395
Birthday	1	Happy Birthday! Wishing you a day filled with laughter, love, and all the wonderful things that make you smile.	111	Another year has passed, and with it came more growth, more memories, and more reasons to be grateful for having you around. I hope today is as wonderful and unforgettable as you deserve, filled with your favorite people, your favorite food, and absolutely no reason to worry about a thing. You bring so much joy into the lives of everyone around you, and today is all about celebrating you. May this new year of life bring you exciting adventures, good health, and endless happiness. Happy Birthday, enjoy every.	513
Birthday	2	Happy Birthday to someone truly wonderful! May your day be as bright, fun, and amazing as you are every day.	108	It is hard to put into words how much joy you bring to the people lucky enough to know you, but I am going to try anyway by saying this: you make everything better just by being there. I hope your birthday is filled with cake, laughter, and every little thing that makes you happy. Here is to another year of chasing your dreams, making memories, and being exactly the incredible person you already are. Cheers to you and to everything wonderful that this new year has in store. Happy Birthday! May this new year bring you nothing but joy and good fortune. Here is to celebrating.	580
Birthday	3	Happy Birthday! May this new year of your life be filled with joy, adventure, and everything your heart desires.	112	Birthdays are the perfect reminder to pause and celebrate not just another year passing, but the incredible person living through it, and that person is you. I hope today brings you all the happiness you deserve and reminds you just how loved and appreciated you truly are. May the year ahead be full of new opportunities, exciting moments, and plenty of reasons to smile. Thank you for being such a bright and wonderful presence in my life. Wishing you the happiest of birthdays, enjoy every single moment! May this new year.	526
Birthday	4	Cheers to you on your special day! Happy Birthday, may it be filled with fun, laughter, and unforgettable memories.	115	There is truly no one quite like you, and today feels like the perfect day to celebrate everything that makes you so wonderfully unique. I hope your birthday is packed with the things you love most, whether that is good food, great company, or a little bit of well deserved relaxation. May the year ahead treat you kindly and bring you closer to everything you have been hoping.	378
Birthday	5	Happy Birthday! Here is to celebrating you today and to another incredible year of growth, joy, and happiness.	110	Every year I get to celebrate your birthday feels like a gift in itself, because it means another year of having you in my life, and that is something truly worth celebrating. I hope today is filled with all your favorite things and surrounded by people who make you feel loved and appreciated. May this new chapter bring you exciting adventures, meaningful moments, and everything you have been quietly hoping for. Thank you for being exactly who you are. Wishing you the happiest.	482
Birthday	6	It is your day! Happy Birthday, may it be filled with sunshine, sweetness, and every little thing that makes you happy.	119	Today is all about you, so I hope you take the time to celebrate yourself the way you deserve, because you spend so much of your time taking care of everyone else. May your birthday be filled with laughter that comes easily, moments that feel effortless, and people who remind you just how special you truly are. Here is to another year of becoming. Enjoy it fully.	365
Birthday	7	Happy Birthday! Wishing you a year ahead that is just as bright, kind, and full of joy as you are every single day.	115	There is something special about celebrating the birthday of someone who makes the world a little brighter just by being in it, and that is exactly what today is about. I hope you feel celebrated, appreciated, and completely surrounded by love, because that is exactly what you deserve. May the year ahead be full of exciting surprises, meaningful connections, and moments worth remembering forever. Thank you for being such a wonderful.	437
Birthday	8	Happy Birthday to you! May today be the beginning of your best year yet, filled with joy, love, and good fortune.	113	With every birthday, I am reminded of just how grateful I am to have you in my life, and today is the perfect day to celebrate everything that makes you so special. I hope you are surrounded by love, laughter, and every little thing that makes you feel happy and appreciated. May the year ahead bring new adventures, exciting opportunities, and moments.	353
Mother's Day	1	Happy Mother's Day! Thank you for your endless love, patience, and the countless ways you make life brighter.	109	Looking back on everything you have done for me, I realize there are simply not enough words to fully capture how grateful I am to have you as my mother. You have been my comfort, my guide, and my biggest supporter through every stage of my life, always giving more than you ever asked to receive in return. Thank you for your patience, your wisdom. With all our love.	368
Mother's Day	2	To the world's most amazing mom, Happy Mother's Day. Your love has shaped who I am in more ways than you know.	110	Every lesson you taught me, every late night you stayed up worrying about me, and every ordinary moment we shared together has quietly built the person I am today, and I owe so much of that to you. You have this incredible ability to make everything feel okay, simply by being there, and I do not think I have ever properly thanked you for that gift. Today, I want you to know how truly grateful I am for your unconditional love and endless support. Happy Mother's Day, you.	474
Mother's Day	3	Happy Mother's Day to an incredible woman who gives so much of herself with love that never seems to run out.	109	There is no version of my life that would look the way it does without your love, guidance, and constant belief in me, even during the moments when I did not quite believe in myself. You have taught me strength, kindness, and what it truly means to care for someone unconditionally. Thank you for every sacrifice, every piece of advice, and every hug that made hard days feel a little easier. Today is all about celebrating you and.	432
Mother's Day	4	Happy Mother's Day! Thank you for being my safe place, my biggest cheerleader, and my forever role model in life.	113	You have this quiet strength that has carried our whole family through good times and hard ones, and I do not think I could ever fully repay you for everything you have given. From the smallest everyday moments to the biggest life lessons, your love has always been the steady thing I could count on. I hope today you get to rest, feel celebrated, and.	352
Mother's Day	5	To my mom, Happy Mother's Day. Your love, wisdom, and endless patience have shaped my life in beautiful ways.	109	Some people are lucky enough to have a mother who feels like a best friend, and I am one of those lucky people because of you. You have guided me through every difficult decision, celebrated every small win, and loved me steadily through every version of myself I have ever been. I hope this Mother's Day reminds you of just how loved, valued, and. With all our love.	367
Mother's Day	6	Happy Mother's Day! Your love has been the constant thread that holds our whole family together, always and forever.	116	I have watched you give so much of yourself over the years, often without asking for anything in return, and it has taught me more about love and sacrifice than any lesson ever could. You have this incredible way of making a house feel like a home and making hard days feel a little more manageable, simply through your presence. Thank you for every ounce of care you.	368
Mother's Day	7	Happy Mother's Day to the woman who taught me kindness, strength, and what unconditional love truly looks like.	111	Every time I think about the kind of person I want to be, I think about you, because so much of my character was quietly shaped by watching how you live your life. You have given endlessly, loved patiently, and shown up for me in ways big and small throughout every stage of my life. Thank you for your guidance, your warmth, and your unwavering belief in me.	359
Mother's Day	8	Happy Mother's Day! Thank you for the love, laughter, and lifetime of memories that only a mother could give.	109	Thinking back over the years, it is the small moments with you that mean the most, the shared laughter, the quiet advice, and the comfort of simply knowing you were always there. You have loved me through every stage of growing up with a patience I still find remarkable. Today I want to celebrate not just what you have done for me, but who you are as a person.	362
Father's Day	1	Happy Father's Day! Thank you for your guidance, strength, and the quiet sacrifices that shaped who I am today.	111	Looking back at everything you have taught me, I realize how much of who I am today came from simply watching how you live, work, and treat the people around you. You showed me what patience looks like, what hard work means, and how to lead with quiet strength instead of loud words. Thank you for every lesson, every piece of advice, and every moment you.	356
Father's Day	2	To an amazing father, Happy Father's Day. Your steady presence and love have meant more than words can say.	107	There is a certain kind of strength that comes from simply being reliable, showing up day after day, and being the steady presence a family can always count on, and that has always been you. You have taught me so much without ever making it feel like a lesson, just by living your life with integrity and care. Thank you for your patience, your humor, and your.	361
Father's Day	3	Happy Father's Day! Thank you for teaching me strength, humor, and how to face life with quiet confidence.	106	Some of my favorite memories are the simplest ones, just spending ordinary time with you, learning things I did not even realize I was learning at the time. You have this way of making hard lessons feel gentle and big moments feel manageable, simply through your calm and steady presence. Thank you for every sacrifice you made quietly and every piece of wisdom you shared along the way. I hope today you feel celebrated for everything you have given our family. Happy Father's Day, with all my gratitude. You are appreciated more than these words could ever fully say.	569
Father's Day	4	Happy Father's Day to the man who taught me hard work, patience, and what it truly means to lead with love.	107	Growing up, I did not always understand the lessons you were teaching me, but looking back now, I see how every one of them shaped the person I have become. You showed up consistently, worked hard quietly, and loved our family in ways that were not always loud but were always deeply felt. Thank you for the guidance, the patience, and the example you set.	356
Father's Day	5	Happy Father's Day! Your wisdom, humor, and unconditional love have shaped my life in more ways than I can count.	113	There are so many small moments I carry with me, conversations, quiet advice, and the simple comfort of your knowing you were always there when it mattered most. You have taught me resilience, humility, and the importance of showing up for the people you love, even when it is not easy. Thank you for every sacrifice you made to give our family a good life. I hope today you feel appreciated for everything you have done, quietly and consistently.	442
Father's Day	6	Happy Father's Day to a truly wonderful dad. Thank you for your patience, strength, and steady, dependable love.	112	You have always been the kind of father who leads by example, showing rather than telling, and I have learned more from watching you than from anything you could have said directly. Thank you for your hard work, your humor during difficult times, and your unwavering support through every chapter of my life. I hope this Father's Day reminds you just how deeply loved and respected you are by everyone in this family. Enjoy today, relax, and know that.	452
Father's Day	7	Happy Father's Day! Thank you for being my role model, my protector, and one of my very favorite people ever.	109	From childhood memories to conversations we still have today, your influence on my life has been constant and quietly profound. You taught me how to handle challenges with a level head, how to treat others with respect, and how to find humor even in difficult situations. Thank you for the countless ways you have supported me, some obvious and many I probably.	361
Father's Day	8	Happy Father's Day to the best dad around. Thank you for your love, your lessons, and your endless patience.	108	Reflecting on everything you have done for our family, I keep coming back to how much of it happened quietly, without fanfare, simply because you cared. You taught me the value of hard work, the importance of kindness, and how to laugh even when things get tough. Thank you for every late night, every piece of advice, and every moment you chose to show up for us. I hope today you feel truly celebrated and appreciated for the incredible father you have always been. Happy Father's.	483
Thank You	1	Thank you so much for your kindness and generosity. It truly meant more to me than I could ever fully express.	110	I have been thinking about what you did, and I keep coming back to how genuinely grateful I am to have someone like you in my life. Kindness like yours does not go unnoticed, and it certainly does not go unappreciated, even if I have not said it enough. You made a real difference, and I want you to know that your thoughtfulness had a bigger impact.	350
Thank You	2	Thank you for everything you did, it meant the world to me and I will not soon forget your kindness and care.	109	There are moments when someone shows up in exactly the way you needed, without being asked, and that is precisely what you did for me. I want you to know how much I appreciate the time, thought, and genuine care you put into helping me, even though it may have seemed small to you. Gestures like yours remind me how lucky I am to have people like you around. Thank you again for your kindness, it truly did not go unnoticed, and it made a real difference in my life. Your kindness continues to make a real difference in my.	523
Thank You	3	Thank you from the bottom of my heart. Your thoughtfulness and support have meant more than words can say.	106	I wanted to take a moment to properly express how grateful I am for everything you have done, because a quick thank you never quite feels like enough. Your generosity and kindness came at exactly the right time, and it made a difference I will genuinely remember. It is people like you who make the hard moments feel a little lighter and the good moments feel.	360
Thank You	4	Just a little note to say thank you. Your generosity and kindness truly made a difference and did not go unnoticed.	115	Sometimes the smallest gestures leave the biggest impact, and that is exactly what happened with what you did for me recently. I want you to know that your thoughtfulness has not gone unnoticed and that I genuinely appreciate everything you did, more than a simple message could ever properly convey. Thank you for your time, your care, and your generosity, all of which.	371
Thank You	5	Thank you for being there when it mattered most. Your kindness and support truly made all the difference to me.	111	There are people who talk about being supportive, and then there are people who actually show up when it counts, and you fall firmly into that second category. I am so grateful for the time, patience, and genuine care you offered me, especially when I needed it the most. Your kindness has left a real and lasting impression, and I wanted to make sure you knew that.	366
Thank You	6	Thank you for your generosity and thoughtfulness. Small gestures like yours truly make the biggest difference.	110	I have been meaning to properly thank you for what you did, because it genuinely made an impact on me that I have not been able to stop thinking about. Your willingness to help, without hesitation or expectation of anything in return, says so much about the kind of person you are. Thank you for your generosity, your time, and the thoughtfulness behind everything you did. I feel truly fortunate to know someone as kind and considerate as you. Please know how much I appreciate you. Your kindness continues to make a real difference in my life. I hope you know just how.	571
Thank You	7	Thank you for your kindness, your patience, and everything you have done to make my life a little bit easier.	109	Every so often someone comes along and makes things easier simply through their willingness to help, and that is exactly the role you have played for me recently. I want to properly acknowledge how grateful I am for your time, your patience, and the genuine care behind everything you have done. It has not gone unnoticed, and it has made a real difference.	357
Thank You	8	A heartfelt thank you for your support and generosity. It has meant more to me than I could ever properly express.	114	I wanted to take a moment to say a proper thank you, because what you did for me deserves more than a quick passing mention. Your generosity and thoughtfulness came at exactly the right time and made a genuine difference in my life. It is rare to find people who give so freely without expecting anything back, and I am grateful every day that you are one of those people. Thank you for your kindness, your patience, and your unwavering support. I truly appreciate you more than you know. Your.	494
Belated Birthday	1	Happy Belated Birthday! I am sorry I missed the day, but I certainly did not forget how special you are to me.	110	I know your actual birthday has come and gone, but I did not want another moment to pass without properly celebrating you, even if it is a little late. Life gets busy and days slip by faster than we expect, but that does not make you any less worth celebrating. I hope your birthday, even after the fact, was filled with love, laughter, and all your.	350
Belated Birthday	2	Better late than never, Happy Belated Birthday! I hope your day was just as wonderful as you truly deserve.	107	I feel a little embarrassed that I am celebrating your birthday a few days late, but I did not want to let it pass without sending you all the good wishes you deserve. I hope the actual day was filled with joy, good company, and everything that made you smile. Consider this message a small reminder that you are appreciated and celebrated, even if the timing was not quite perfect. Happy Belated Birthday, and here is to making up for lost time with even more celebration ahead. Better a.	489
Belated Birthday	3	So sorry this is late, but Happy Belated Birthday! Wishing you all the joy your special day truly deserved.	107	I cannot believe I let your birthday slip by without reaching out on the actual day, but please know that thinking of you late is still much better than not thinking of you at all. I hope your birthday was everything you hoped for, filled with celebration, good food, and people who love you. Even though this wish is arriving a little behind schedule, the sentiment behind it is completely genuine. Happy Belated Birthday, and here is.	436
Belated Birthday	4	Oops, Happy Belated Birthday! I hope you had an amazing day even without my timely wishes joining the celebration.	114	I promise this delay does not reflect how much I care, it simply reflects how quickly time seems to slip away these days. I hope your birthday was filled with everything you love, good company, delicious food, and plenty of reasons to smile. Even though I am a little behind, I still wanted to make sure you felt celebrated and appreciated, because you absolutely deserve it. Happy Belated Birthday, and here is to squeezing a little extra celebration out of this year for you. Better a.	487
Belated Birthday	5	Happy Belated Birthday! Consider this an extension of your celebration, because you deserve more than just one day.	115	I know I am a few days behind, but I refused to let your birthday pass without properly celebrating someone as wonderful as you. I hope the actual day was filled with joy, laughter, and all the little things that make birthdays special. Since I am running a bit late, let us just call this the unofficial extension of your birthday celebration, because.	353
Belated Birthday	6	A little late, but wholeheartedly meant, Happy Belated Birthday! I hope your day was filled with joy and love.	110	I am sorry I missed sending my wishes on the actual day, but that does not mean you were not on my mind, because you absolutely were. I hope your birthday was everything you wanted, filled with good company, great food, and plenty of moments worth remembering. Even a little late, I wanted to make sure you knew just how much you are appreciated and celebrated. Happy Belated Birthday, and here.	395
Belated Birthday	7	Happy Belated Birthday! Better late wishes than none at all, and I truly hope your day was full of happiness.	109	I feel a bit sheepish sending this after the fact, but I did not want to let your birthday pass without properly acknowledging how special you are. I hope your actual birthday was filled with celebration, laughter, and everyone you love gathered around you. Even though this message is arriving fashionably late, the warmth and love behind it are completely on time. Happy Belated Birthday, and here is to celebrating you.	422
Belated Birthday	8	So this is a bit overdue, but Happy Belated Birthday! I hope your special day was everything you wished for.	108	I cannot promise punctuality, but I can promise that you were absolutely on my mind even though this message is arriving late. I hope your birthday was filled with wonderful moments, good company, and all the little joys that make the day feel truly special. Better late wishes from the heart than none at all, right? Consider this a small continuation of your celebration. Happy.	380
Friendship	1	To my amazing friend, thank you for the laughter, support, and memories that make life so much better with you.	111	Friendship like ours is rare, the kind where distance and time never really change how comfortable we are with each other. You have been there through the good times and the hard ones, always ready with honesty, humor, or just quiet company when that is what I needed most. I do not think I say it enough, but having you in my life has made everything better. Thank you for being exactly the kind of friend everyone hopes to find. Here is to many.	447
Friendship	2	Friends like you are hard to find and impossible to replace. Thank you for always being there through everything.	113	I have thought a lot about what makes our friendship so special, and I keep coming back to the fact that you accept me completely, without judgment, even on my worst days. You make hard times easier just by being present, and you make good times even better by sharing in the joy of them with me. Thank you for the laughter, the honesty, and the countless memories we have built.	379
Friendship	3	Thank you for being the kind of friend who shows up, listens well, and makes life feel a whole lot brighter.	108	Some friendships fade with time, but ours has only grown stronger, and I think that says a lot about the kind of friend you are. You have this incredible ability to make me feel understood without needing to explain myself, and that kind of connection is not something I take for granted. Thank you for every conversation, every inside joke, and every moment you have chosen to show up for me. I truly cherish our.	414
Friendship	4	Here is to friendship, laughter, and years of memories that only get better the longer we know each other.	106	Looking back at everything we have shared together, I realize how lucky I am to have found a friend who genuinely gets me the way you do. You have been my sounding board, my comic relief, and my honest voice of reason more times than I can count, and I appreciate every single one of those moments. Thank you for the years of friendship, the shared memories, and the unwavering support you have.	395
Friendship	5	Thank you for being such a wonderful friend, one who makes ordinary days feel a little brighter and more fun.	109	There is something incredibly comforting about a friendship where you do not have to try too hard, where things just feel easy and natural, and that is exactly what we have. You have supported me through changes, celebrated my wins, and stuck around through my messier moments without ever making me feel judged. Thank you for your loyalty, your humor, and your genuine kindness over the years. I feel truly grateful to call you my friend, and I hope you know how much you mean to me. I do not know what I would do without a friend like you. Here is to many more years of laughter and memories.	594
Friendship	6	To a friend who feels like family, thank you for your loyalty, honesty, and the laughter that never seems to end.	113	It is rare to find someone who feels less like a friend and more like family, but that is exactly what you have become to me over the years. You have this way of knowing exactly what to say, whether I need encouragement, honesty, or just someone to laugh with about nothing in particular. Thank you for your patience, your loyalty, and every memory we have built together along the way. I am so grateful to have someone like you by my side. Here is to us, always. I do not know what I would do without a friend like you. Here is to many more years of laughter and memories together.	582
Friendship	7	Thank you for being my constant, the friend who stays no matter what changes around us over the years together.	111	Life has a way of shifting and changing, but our friendship has always felt like a steady, reliable constant through every version of it. You have celebrated my successes, supported me support through hard times, and never once made me feel like our friendship needed to be perfect to be real. Thank you for your honesty, your humor, and the comfort of knowing you are always just a call away. I cherish our friendship deeply and feel truly lucky to have you in my life. I do not know what I would do without a.	503
Friendship	8	To my dear friend, thank you for the years of support, laughter, and honesty that have shaped so many memories.	111	Reflecting on our friendship over the years, I keep noticing how naturally comfortable everything feels between us, no matter how much time has passed since we last talked. You have this rare gift of making people feel heard and valued, and I have been lucky enough to experience that firsthand more times than I can count. Thank you for your loyalty.	351
Sympathy	1	With deepest sympathy. May the love of family and friends bring you comfort and peace during this difficult time.	113	There are no words that can truly ease the pain of losing someone so dear, but please know that you are being thought of and held close during this incredibly difficult time. Grief moves in its own way and its own time, and there is no right way to move through it. Please lean on the people around you, and know that it is okay to feel whatever you are feeling right now. Wishing you moments of peace.	402
Sympathy	2	Thinking of you during this difficult time. May cherished memories bring you comfort in the days that follow.	109	I am so deeply sorry for your loss, and I wanted you to know that you are being held in thought during this painful time. Losing someone you love leaves a space that nothing else can quite fill, but I hope the memories you shared together continue to bring you comfort as time passes. Please do not hesitate to lean on those around you, and allow yourself the grace to grieve in whatever way feels.	398
Sympathy	3	With heartfelt condolences. Wishing you strength, comfort, and peace as you navigate this profound and painful loss.	116	There is truly nothing that can make a loss like this feel easier, but I hope you find some comfort in knowing how many people are thinking of you and holding you close right now. Grief can feel overwhelming and unpredictable, so please be gentle with yourself as you move through it, one moment at a time. The love and memories you shared will always.	352
Sympathy	4	My deepest condolences to you and your family. May you find comfort in the love that surrounds you right now.	109	Words feel especially small in moments like this, but I wanted to reach out and let you know that you are being thought of with care during this incredibly hard time. The loss of someone so loved leaves behind a grief that takes time and patience to move through, and there is no timeline you need to follow. Please allow yourself to lean on family and friends, and know that it is okay to feel however you are feeling right now. Sending you comfort, strength, and heartfelt sympathy. Please know that you are held in thought during this time. May you find small moments of.	574
Sympathy	5	Sending you comfort and strength during this time of loss. You are being thought of with love and deep care.	108	I am so sorry for the pain you are carrying right now, and I wanted to make sure you knew you are not alone in this. Grief has a way of arriving in waves, sometimes overwhelming and sometimes quiet, and there is no wrong way to experience it. I hope the love you shared and the memories you carry continue to bring you moments of comfort in the days ahead. Please.	364
Sympathy	6	With sympathy and love. May you find peace in cherished memories and comfort in the support that surrounds you.	111	There is nothing that can truly soften a loss like this, but I hope it helps to know how many people are thinking of you and wishing you strength right now. Take the time you need to grieve, to remember, and to feel whatever comes up without judgment or rush. The bond you shared does not disappear, it simply becomes something you carry with you differently now. Please reach out if you ever need someone to.	409
Sympathy	7	Thinking of you with love during this painful time. May comfort find you, even in the smallest of quiet moments.	112	I am deeply sorry for your loss, and I have been thinking of you and your family constantly since hearing the news. Losing someone so important leaves behind a kind of quiet that is hard to describe, and I hope you give yourself permission to grieve fully and honestly, without rushing the process. The love you shared will always remain, even as things around you change. Please know that support and care surround you, even on the days it feels hardest to notice. With sincere sympathy. Please know that you are held in thought during this.	542
Sympathy	8	With deepest sympathy for your loss. Wishing you moments of peace, strength, and comfort in the days ahead.	107	There are truly no perfect words for a time like this, but please know that you are held closely in thought during this painful season of loss. Grief can feel isolating, but you are surrounded by people who care deeply and want to support you in any way they can. Please allow yourself the space to feel everything you are feeling, without judgment or.	352
Missing You	1	Missing you more than words can say. Counting down the days until we get to see each other again very soon.	107	Some days the distance between us feels manageable, and other days it feels like entirely too much, but either way, you are always somewhere in my thoughts. I find myself wanting to share little moments with you throughout the day, the funny things that happen, the songs that remind me of you, the quiet realization that I wish you were here. Distance is hard, but it has.	373
Missing You	2	I miss you more than I can properly put into words. Thinking of you and wishing we were together right now.	107	There is a particular kind of quiet that settles in when someone important is far away, and I have been feeling it more than usual lately. I keep catching myself wanting to tell you things throughout the day, only to remember you are not just a room away right now. Even with the distance, you are never far from my thoughts, and I hold onto the memory of your laugh and the comfort of your presence. I cannot wait until we are together again. Missing you more than words can say. Until we meet again, know that you are always on my mind. The distance is temporary.	565
Missing You	3	Wherever you are, know that you are missed and thought of constantly, and I cannot wait to see you again soon.	110	Distance has a way of making the small things feel bigger, the sound of your voice, the sight of your handwriting, the memory of an ordinary afternoon spent together. I find myself thinking of you at the most random moments throughout the day, wishing you were simply here to share them with me. Even though we are apart right now, that has never once changed how much you mean to me or how much I look forward to seeing.	421
Missing You	4	You are missed more than you know. Sending you love across the distance and counting the days until we reunite.	111	Being apart from someone you care about has a strange way of making even the smallest memories feel precious, and lately I have been holding onto quite a few of those memories of you. I think about our last conversation often, replaying it like a favorite song, and I find myself looking forward to the next time we get to talk or, even better, see each other in person. The distance is hard, but it has never once dimmed how much you mean to me. Missing you deeply, always. Until we meet again.	495
Missing You	5	Thinking of you today and wishing the miles between us were just a little bit shorter. Miss you more than ever.	111	There are days when the distance feels completely fine and days when it feels like far too much, and today has definitely been one of the harder ones. I keep thinking about the last time we were together and looking forward to the next time, whenever that may be. Even with all this distance between us, you remain a constant presence in my thoughts and my heart. I cannot wait until we are back together again, sharing ordinary moments the way we used to. Missing you always and completely. Until we.	501
Missing You	6	Missing your presence more than words can capture. Sending you love, thoughts, and hopes for a reunion very soon.	113	It is strange how absence can make even the smallest details feel significant, the way you laugh, the way you tell stories, the comfort of simply being in the same room together. I find myself thinking of you constantly, wishing the distance between us were shorter and the time until we reunite were quicker. Please know that even from far away, you.	351
Missing You	7	Even from far away, you are always close in my thoughts. Missing you today and looking forward to seeing you soon.	114	There is something about missing someone that makes you appreciate them even more, and lately I have found myself appreciating you in a hundred different ways throughout each day. I think about our conversations, our shared memories, and the simple comfort of your company, wishing all of it were a little closer than it currently is. The distance. Missing you always.	368
Missing You	8	You are on my mind constantly, even from far away. Missing you and counting down until we can be together soon.	111	Distance tends to have a strange effect where it makes you notice all the little things you might have otherwise taken for granted, and I have definitely been noticing how much I miss having you nearby. Every day brings some small reminder of you, a song, a memory, an inside joke that only makes sense to us. Even though we are apart right now, my thoughts are with you constantly, and I cannot wait for the moment we are.	423
Troubled Relationship	1	I know things have been hard between us lately, but I still care about you and I truly want us to work this through.	116	I have been thinking a lot about where things stand between us, and even though it has not been easy, I want you to know that my care for you has not changed. Relationships go through difficult seasons, and I believe ours is worth the effort it takes to work through this one. I am willing to listen, to be honest, and to be patient as we figure out how.	354
Troubled Relationship	2	Things have been tough between us, but I still believe in what we have, and I truly hope we can find our way back.	114	I know things have felt strained lately, and that is not lost on me, but I wanted you to know that I have not given up on us. Every relationship faces rough patches, and while ours certainly has not been easy recently, I still believe there is something worth fighting for underneath all the tension. I am willing to have the hard conversations, to really listen, and to be patient as we work through this together. I.	418
Troubled Relationship	3	I know we have been struggling lately, but I still value what we have, and I hope we can rebuild it together.	109	It has not escaped me how difficult things have felt between us recently, and I imagine it has been hard for you too. I wanted to reach out and let you know that despite everything, I still care deeply and still believe our relationship is worth repairing. I am ready to listen honestly, to take responsibility where it is needed, and to work through whatever has come between us with patience and care. I hope we can find our way back to each other, even if it takes time and effort to get there. I truly believe we.	517
Troubled Relationship	4	I know things feel uncertain right now, but I still care about you, and I hope we can talk this through honestly.	113	The distance that has grown between us lately has weighed on me more than I have probably said, and I did not want another day to pass without reaching out. I still care about you and about what we have built together, even during this difficult stretch. I am open to talking honestly, listening without defensiveness, and doing the work it takes to repair what feels broken right now. I hope we can find a path.	412
Troubled Relationship	5	I know we have hit a rough patch, but I still believe in us, and I hope we can work through this side by side.	110	Lately things have felt more difficult between us than I would like, and I have been sitting with that discomfort, trying to figure out the right way forward. I want you to know that despite the tension, I still care deeply about you and about repairing what has come between us. I am willing to be honest, to really listen, and to be patient as we work through whatever needs healing. I hope we can find our way back to a place of understanding and closeness again, together. I truly believe we can find our way back to each other. Whatever happens, I am willing to put in the work it.	586
Troubled Relationship	6	I know things have been strained lately, but I truly want to understand you better and work toward healing this.	112	I have noticed the distance between us growing, and rather than letting it continue quietly, I wanted to address it honestly instead. I still care about you and about this relationship, even through this difficult period. I am willing to really listen to how you are feeling, to be honest about my own perspective, and to work patiently toward rebuilding the trust and connection that feels shaky right now. I hope we can move through this together, with.	455
Troubled Relationship	7	Even though things have been difficult lately, I still care about us, and I hope we can find a way forward together.	116	I know the tension between us has not been easy for either of us, and I have been thinking about how to approach it honestly rather than letting it linger unspoken. I still value this relationship and believe it is worth putting in the effort to repair. I am ready to listen without judgment, to be honest about where I have fallen short, and to work.	351
Troubled Relationship	8	I know our relationship has felt strained recently, but I still want us to grow through this together, honestly.	112	I have been reflecting on the tension between us lately, and I did not want to let it sit unaddressed any longer. Despite the difficulty, I still care about you and about the future of what we have built together. I am willing to communicate honestly, to really hear your side, and to take responsibility for my part in the difficulties we have faced. I hope we can move forward from this stronger and more understanding than before, choosing patience and honesty over silence and distance. I truly believe we can find our way back to each other. Whatever happens, I am.	570
Advice	1	Trust yourself a little more. You have made it through every hard day so far, and this one will be no different.	112	Whenever life feels uncertain, it helps to remember just how far you have already come and how much strength it took to get here, even on the days it did not feel like strength at all. You do not need to have every answer right now, you just need to keep moving forward one honest step at a time. Trust your instincts, be patient with yourself, and remember that.	363
Advice	2	Take things one step at a time. You do not need to have it all figured out today, just take the next small step.	112	It is easy to feel overwhelmed when you look at everything all at once, but nobody actually moves through life that way, they move through it one decision, one day, one small step at a time. Give yourself permission to not have all the answers right now, and trust that clarity tends to come with time and patience rather than pressure. Be gentle with yourself.	361
Advice	3	Be patient with yourself. Growth takes time, and you are allowed to move at whatever pace feels right for you.	110	Sometimes the hardest part of any challenge is being kind to yourself while you work through it, especially when it feels like everyone else has things figured out and you do not. The truth is, nobody actually has it all figured out, everyone is simply doing their best with what they know at the time. Give yourself the same grace you would offer a close friend in your.	371
Advice	4	Listen to your gut, it usually knows more than you give it credit for. Trust yourself to make the right choice.	111	When decisions feel overwhelming, it can help to strip away all the outside noise and simply ask yourself what feels right, deep down, before all the second guessing sets in. Your instincts have gotten you this far for a reason, and they deserve more trust than you probably give them on a daily basis. Take your time, weigh your options honestly, but do not forget to listen to that quiet inner voice that usually knows more than you.	435
Advice	5	Do not be afraid to ask for help. Strength is not about doing everything alone, it is about knowing when to lean.	113	There is a common misconception that asking for help somehow makes you weaker, when in reality it takes real courage to admit you cannot do everything entirely on your own. The people who care about you want to help, and letting them do so is not a burden, it is simply what relationships are for. Give yourself permission to lean on others when things.	353
Advice	6	Focus on what you can control, and let go of the rest. Peace comes from where you place your energy each day.	109	So much of our stress comes from trying to manage things that were never really within our control in the first place, and learning to let go of that is one of the hardest but most freeing lessons there is. Focus your energy on the decisions, actions, and attitude that are genuinely yours to shape, and try to release the rest, even when it feels difficult. Progress rarely looks like perfect control, it looks like.	417
Advice	7	Do not compare your journey to anyone else's. Your timeline is your own, and it is unfolding exactly as it should.	114	It is so easy to look around and feel like everyone else is further along, doing better, or figuring things out faster, but comparison rarely tells the whole story of what someone else is actually going through. Your path does not need to look like anyone else's to be meaningful or valid, it simply needs to be honestly yours. Trust the pace you are moving at, even on the days it feels slow.	393
Advice	8	Give yourself credit for how far you have come. Progress is still progress, even when it feels painfully slow.	110	It is easy to focus on everything that still feels unfinished and forget to acknowledge everything you have already overcome to get to this exact point. Growth is rarely loud or obvious in the moment, it usually happens quietly, one small decision at a time, until one day you look back and realize just how far you have actually come. Give yourself permission.	361
Wedding	1	Congratulations on your wedding! Wishing you a lifetime of love, laughter, and adventures shared together always.	113	Watching two people commit to building a life together is one of the most beautiful things to witness, and today that beautiful thing is happening for the two of you. May your marriage be filled with the kind of love that grows stronger through every season, the patience to weather life's challenges together, and the laughter that keeps even ordinary days feeling special. Here is to a lifetime of partnership, adventure, and.	428
Wedding	2	Wishing you both a lifetime of happiness, love, and partnership as you begin this beautiful journey together.	109	There is something truly special about watching two people who love each other deeply commit to a lifetime together, and today marks the beginning of exactly that for you both. May your marriage be built on a foundation of trust, laughter, and genuine partnership through every high and low that life brings your way. Here is to countless shared memories, quiet.	362
Wedding	3	Congratulations to the happy couple! May your marriage be filled with love, laughter, and endless shared happiness.	115	Today is the beginning of a beautiful new chapter, one built on the love and commitment you have chosen to share with one another for the rest of your lives. May you continue to choose each other every single day, through the easy seasons and the harder ones, always finding your way back to laughter and love. Here is to building a home together. Wishing you joy.	364
Wedding	4	Two hearts becoming one, congratulations on your wedding! Wishing you a marriage filled with love and joy always.	113	There is nothing quite like witnessing two people commit to loving each other fully, through every version of life that is still ahead of them, and that is exactly what is happening today. May your marriage be filled with genuine partnership, plenty of laughter, and the kind of love that only continues to deepen as the years go by. Here is to a lifetime of shared adventures, quiet everyday moments, and unwavering support for one another. Congratulations, and wishing you both endless happiness as husband and wife. May your love.	533
Wedding	5	Congratulations on your wedding day! May your love story continue to grow more beautiful with every passing year.	113	Today marks such a meaningful beginning, the start of a life built together, filled with shared dreams, everyday moments, and a love that continues to grow deeper with time. May your marriage be a source of comfort, joy, and genuine partnership through every season life brings your way. Here is to a lifetime of laughter, adventure, and unwavering support for one another, no matter what challenges or celebrations come along the path ahead. Congratulations to.	462
Wedding	6	Wishing the newlyweds a marriage filled with love, laughter, and a lifetime of beautiful memories together always.	114	There is something truly wonderful about celebrating two people who have found in each other a partner for life, and today is all about honoring exactly that. May your marriage be filled with patience, understanding, and a love that only strengthens as the years continue to pass. Here is to building a life together full of shared laughter, quiet comfort, and.	361
Wedding	7	Congratulations on tying the knot! May your marriage be blessed with love, laughter, and a lifetime of happiness.	113	Today is the beginning of something truly beautiful, a lifelong partnership built on love, trust, and the choice to grow together through every stage of life. May your marriage be filled with laughter on the easy days and patience on the harder ones, always finding your way back to one another. Here is to countless shared adventures, quiet everyday.	351
Wedding	8	Here is to the happy couple! Congratulations on your wedding, may your marriage be filled with love and joy.	108	Watching the beginning of a marriage is watching the start of a beautiful shared story, one filled with love, partnership, and countless memories still waiting to be made. May you continue to choose one another every day, celebrating the joyful moments and supporting each other through the harder ones with equal care. Here is to a lifetime built on trust, laughter, and genuine companionship. Congratulations on your wedding day, and wishing you both endless happiness as you begin this wonderful new chapter together. May your love only continue to grow deeper with.	569
Good Luck	1	Wishing you the very best of luck! I know you have what it takes to succeed at whatever comes your way next.	108	Whatever challenge you are about to take on, I want you to know how much confidence I have in your ability to handle it well. You have prepared, you have worked hard, and now it is simply time to trust yourself and let that preparation carry you through. Try not to let nerves overshadow how genuinely capable you are, because you truly are ready for this. Wishing you clarity.	377
Good Luck	2	Good luck! Whatever happens, know that your hard work and effort have already prepared you for this moment.	107	As you head into this next challenge, I hope you feel confident in everything you have already put into getting ready for it. You have worked hard, stayed focused, and shown real dedication, and that kind of preparation deserves to pay off. Try to trust yourself and stay calm, because you are more capable than the nerves might be telling you right now. Wishing you good luck, clear.	384
Good Luck	3	Sending you good luck and good vibes! I know you are going to do amazing, whatever challenge lies ahead of you.	111	I wanted to send a little extra encouragement your way as you head into this next big moment, because I know how much effort you have already put in to get here. Trust the preparation you have done and give yourself credit for how far you have already come. Nerves are normal, but do not let them convince you that you are anything less than ready for this. Wishing you clarity, confidence, and plenty of good luck for whatever comes next. I have absolutely no doubt you are going to succeed. Trust yourself, you have already done the.	535
Good Luck	4	Good luck out there! Trust in your preparation, believe in yourself, and remember just how capable you truly are.	113	Whatever you are about to face, I want you to know that you have already done the hard part, the preparation, the effort, and the persistence it took to get to this point. Now all that is left is to trust yourself and let everything you have worked on carry you through with confidence. Try to stay calm, breathe through the nerves, and remind yourself just how ready you actually are. Wishing you the very best of luck today and every step of the way.	452
Good Luck	5	Wishing you all the luck in the world! Go show everyone exactly what you are capable of, because you have got this.	115	As this important moment approaches, I want you to remember just how much work and dedication you have already poured into getting ready for it. Trust yourself, stay confident, and remember that nerves are simply a sign that this matters to you, not a sign that you are unprepared. You have everything within you already to handle whatever comes next.	351
Good Luck	6	Good luck today! Take a deep breath, trust your preparation, and remember just how far you have already come.	109	Big moments like this can feel overwhelming, but I want you to remember that you have already done so much work to get to this exact point. Trust that preparation, breathe through any nerves, and give yourself credit for the effort and dedication it took to be ready for this. Whatever the outcome, you should be proud of how hard you have worked to.	350
Good Luck	7	Sending good luck your way! I believe in you completely, and I know you are going to handle this beautifully.	109	As you step into this next challenge, I hope you can feel the confidence and support of everyone rooting for you from here, myself included. You have put in real effort to prepare for this moment, and now it is time to trust that work and let it guide you through with a clear head. Nerves are simply proof that you care, not proof that you are not ready. Wishing you good luck, calm confidence, and a truly successful outcome. I know you are going to do.	455
Good Luck	8	Good luck! Whatever the outcome, remember how proud everyone already is of the effort you have put into this.	109	Before you head into this next big moment, I wanted to remind you just how much hard work and dedication you have already shown to get here. Trust that preparation, breathe deeply, and remember that you are far more capable than any nerves might be telling you right now. Regardless of the outcome, the effort and growth you have shown along the way already deserve real recognition and pride. Wishing you clarity, confidence, and the very best of luck.	453""";
  
  final List<Map<String, dynamic>> cardsToInsert = [];
  final lines = rawData.trim().split('\n');
  
  for (var line in lines) {
    final parts = line.split('\t');
    if (parts.length >= 6) {
      final categoryName = parts[0].trim().toLowerCase();
      final cardNumber = parts[1].trim();
      final frontText = parts[2].trim();
      final insideText = parts[4].trim();
      
      final categoryId = categoryNameToId[categoryName];
      if (categoryId != null) {
        final defaults = categoryIdToCardDefaults[categoryId];
        if (defaults != null) {
          cardsToInsert.add({
            'category_id': categoryId,
            'title': '${parts[0].trim()} $cardNumber',
            'cover_image_url': defaults['cover_image_url'],
            'default_front_message': frontText,
            'default_inside_message': insideText,
            'price': 5.99,
            'is_featured': (cardNumber == '1' && categoryName == 'love') || (cardNumber == '1' && categoryName == 'birthday'), // feature the first card of some categories
            'color_value': defaults['color_value']
          });
        }
      } else {
        print('Warning: Category $categoryName not found!');
      }
    }
  }
  
  print('✅ Parsed ${cardsToInsert.length} cards.');
  
  // 5. Bulk insert
  const int batchSize = 10;
  for (var i = 0; i < cardsToInsert.length; i += batchSize) {
    final end = (i + batchSize < cardsToInsert.length) ? i + batchSize : cardsToInsert.length;
    final batch = cardsToInsert.sublist(i, end);
    await client.from('cards').insert(batch);
  }
  
  print('🎉 All 112 cards have been uploaded seamlessly!');
  exit(0);
}
